In [33]:
import pandas as pd 
dataset = pd.read_csv('C:/Users/DELL/Downloads/6th semester/Web Mining/Lab/iris.csv')
print(dataset.head())
X = dataset.iloc[:, 0:4].values
y = dataset.iloc[:, 4].values

   sepal_length  sepal_width  petal_length  petal_width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20, random_state=42) 
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [43]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
import numpy as np
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred, average='weighted'))
print(precision_score(y_test, y_pred, average='weighted'))
print(f1_score(y_test, y_pred, average='weighted'))
print(classification_report(y_test, y_pred))
print("19BCE0506 Pratyush Kumar")

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
1.0
1.0
1.0
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

19BCE0506 Pratyush Kumar
